### ISSUE TITLE
Publish on crate.io?

### ISSUE THREAD

**Issue by tsturzl** [cjqed/rs-natural#9]
I use rs-natural in a few of my hobby projects, and I notice that this project isn't on crates.io. This creates a problem if I myself would like to publish one of my projects that uses rs-natural to crates.io. Is there any reason that it is not? I know [rust-stem](https://github.com/mrordinaire/rust-stem) is also not on crates.io, but issue #3 seems to address this. If this is the only thing holding it back I'd be more than happy to make a PR where rust-stem is included. There shouldn't be any licensing issues since both projects are MIT licensed.

**Comment by cjqed** [comment]
No reason except that it wasn't around when I first made it. It should be good to do now, I'll work on that today

**Comment by cjqed** [comment]
Should be good to go as `natural = 0.2.1`: https://crates.io/crates/natural
